webshop_projekt/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using webshop_projekt.Data;
using webshop_projekt.Misc;
using webshop_projekt.Models;

namespace webshop_projekt.Controllers
{
    [Authorize(Roles =OvlastiKorisnik.Administrator + "," + OvlastiKorisnik.Moderator)]
    public class HomeController : Controller
    {
        ProizvodDbContext db = new ProizvodDbContext();
        KategorijaDbContext kategorija = new KategorijaDbContext();
        ProizvodDbContext proizvod = new ProizvodDbContext();

        [AllowAnonymous]
        public ActionResult Index()
        {
            ViewBag.Model = new Proizvod();
            ViewBag.Kategorije = kategorija.Kategorijas.ToList();
            ViewBag.Proizvodi = proizvod.Proizvods.ToList();
            return View(db.Proizvods.ToList());
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

webshop_projekt/Controllers/KosaricaItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using webshop_projekt.Data;
using webshop_projekt.Misc;
using webshop_projekt.Models;
using webshop_projekt.Reports;

namespace webshop_projekt.Controllers
{
    [Authorize(Roles = OvlastiKorisnik.Administrator)]
    public class KosaricaItemsController : Controller
    {
        KosaricaDbContext db = new KosaricaDbContext();
        ProizvodDbContext proizvodi = new ProizvodDbContext();

        [AllowAnonymous]
        // GET: KosaricaItems
        public ActionResult Index()
        {
            return View(db.KosaricaItems.ToList());
        }

        // GET: KosaricaItems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KosaricaItem kosaricaItem = db.KosaricaItems.FirstOrDefault(x => x.Id == id);
            if (kosaricaItem == null)
            {
                return HttpNotFound();
            }
            return View(kosaricaItem);
        }

        [AllowAnonymous]
        public ActionResult DodajUKosaricu(int id)
        {
            /*if (id == null) { 
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }*/

            Proizvod proizvod = proizvodi.Proizvods.Find(id);

            if (proizvod == null)
            {
                return HttpNotFound();
            }

            KosaricaItem kosaricaItem = new KosaricaItem { Id = id, Cijena = (decimal)proizvod.Cijena, Naziv = proizvod.Naziv, Kolicina = 1 };
            db.KosaricaItems.Add(kosaricaItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        // GET: KosaricaItems/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: KosaricaItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Naziv,Cijena")] KosaricaItem kosaricaItem)
        {
            if (ModelState.IsValid)
            {
                db.KosaricaItems.Add(kosaricaItem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(kosaricaItem);
        }

        [AllowAnonymous]
        // GET: KosaricaItems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KosaricaItem kosaricaItem = db.KosaricaItems.FirstOrDefault(x => x.Id == id);
            if (kosaricaItem == null)
            {
                return HttpNotFound();
            }
            return View(kosaricaItem);
        }

        [AllowAnonymous]
        // POST: KosaricaItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            KosaricaItem kosaricaItem = db.KosaricaItems.FirstOrDefault(x => x.Id == id);
            db.KosaricaItems.Remove(kosaricaItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [AllowAnonymous]
        public ActionResult IspisRacuna(string Naziv, int? Kolicina, decimal? Cijena)
        {
            var stvari = db.KosaricaItems.ToList();

            if(!String.IsNullOrEmpty(Naziv))
            {
                stvari = stvari.Where(x => x.Naziv.ToUpper().Contains(Naziv.ToUpper())).ToList();
            }
            if (!String.IsNullOrEmpty(Naziv))
            {
                stvari = stvari.Where(x => x.Kolicina == Kolicina).ToList();
            }
            if (!String.IsNullOrEmpty(Naziv))
            {
                stvari = stvari.Where(x => x.Cijena == Cijena).ToList();
            }
            KosaricasReport kosaricasReport = new KosaricasReport();
            kosaricasReport.ListaKosarica(stvari);

            return File(kosaricasReport.Podaci, System.Net.Mime.MediaTypeNames.Application.Pdf, "RacunKosarica.pdf");
        }

        [AllowAnonymous]
        public ActionResult ObrisiKosaricu()
        {
            var listaKosarica = db.KosaricaItems.ToList();

            foreach (var kosaricaItem in listaKosarica)
            {
                db.KosaricaItems.Remove(kosaricaItem);
            }

            db.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

webshop_projekt/Controllers/ProizvodsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Runtime.InteropServices;
using System.Web;
using System.Web.Mvc;
using webshop_projekt.Data;
using webshop_projekt.Misc;
using webshop_projekt.Models;

namespace webshop_projekt.Controllers
{
    [Authorize(Roles = OvlastiKorisnik.Administrator)]
    public class ProizvodsController : Controller
    {
        ProizvodDbContext db = new ProizvodDbContext();
        KategorijaDbContext kategorija = new KategorijaDbContext();
        ProizvodacDbContext proizvodac = new ProizvodacDbContext();

        // GET: Proizvods
        public ActionResult Index()
        {
            return View(db.Proizvods.ToList());
        }

        // GET: Proizvods/Details/5
        [OverrideAuthorization]
        [Authorize]
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proizvod proizvod = db.Proizvods.FirstOrDefault(x=>x.idProizvod == id);
            if (proizvod == null)
            {
                return HttpNotFound();
            }
            return View(proizvod);
        }

        // GET: Proizvods/Create
        public ActionResult Create()
        {
            ViewBag.Kategorije = kategorija.Kategorijas.ToList();
            ViewBag.Proizvodaci = proizvodac.Proizvodacs.ToList();
            return View();
        }

        // POST: Proizvods/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Naziv,Cijena,Proizvodac,Kategorija,Opis")] Proizvod proizvod)
        {

            if (ModelState.IsValid)
            {
                db.Proizvods.Add(proizvod);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Kategorije = kategorija.Kategorijas.ToList();
            ViewBag.Proizvodaci = proizvodac.Proizvodacs.ToList();
            return View(proizvod);
        }

        // GET: Proizvods/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proizvod proizvod = db.Proizvods.FirstOrDefault(x => x.idProizvod == id);
            if (proizvod == null)
            {
                return HttpNotFound();
            }
            return View(proizvod);
        }

        // POST: Proizvods/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Proizvod proizvod)
        {
            if (ModelState.IsValid)
            {
                db.Entry(proizvod).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(proizvod);
        }

        // GET: Proizvods/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proizvod proizvod = db.Proizvods.FirstOrDefault(x => x.idProizvod == id);
            if (proizvod == null)
            {
                return HttpNotFound();
            }
            return View(proizvod);
        }

        // POST: Proizvods/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Proizvod proizvod = db.Proizvods.FirstOrDefault(x => x.idProizvod == id);
            db.Proizvods.Remove(proizvod);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

webshop_projekt/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

webshop_projekt/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

webshop_projekt/Views/Home/Index.cshtml
@model IEnumerable<webshop_projekt.Models.Proizvod>
@{
    ViewBag.Title = "Početna";
    var model = ViewBag.Model;
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">Web shop</h1>
        <p class="lead">Web shop sa svom potrebnom periferijom i komponentama.</p>
        <div style="display:flex; justify-content:flex-end">
            <div id="desno" style="display:flex; float:inline-end">
                <p style="display:flex;float:right">
                    <h5 style="display:flex; align-content:center; margin-top:5px">Tražilica: </h5>
                    @using (Html.BeginForm("Index", "Home", FormMethod.Get))
                    {
                    <p>
                        @Html.TextBox("Naziv")
                        <button type="submit" class="btn btn-secondary">Traži</button>
                    </p>
                    }
                    <p>
                    <button type="button" onclick="window.location.href='@Url.Action("Index", "Home")'" class="btn btn-secondary">Ukloni filter</button>
                    </p>
                </div>

        </div>
    </section>
    <hr />

    <div>
        @if (string.IsNullOrEmpty(Request.QueryString["Naziv"]))
        {
            foreach (var item in Model)
            {
                <div style="border:solid 1px gray; border-radius:10px; display:inline-flex; flex-direction:column; min-width:300px; max-width:800px; min-height:100px">
                    <ol>
                        <ui><b>Naziv:</b>@Html.DisplayFor(modelItem => item.Naziv)</ui>
                        <br />
                        <ui><b>Proizvođač:</b>@Html.DisplayFor(modelItem => item.Proizvodac)</ui>
                        <br />
                        <ui><b>Cijena:</b>@Html.DisplayFor(modelItem => item.Cijena)</ui>
                    </ol>
                    @Html.ActionLink("Dodaj u košaricu", "DodajUKosaricu", "KosaricaItems", new { id = item.idProizvod }, new { @class = "btn btn-info" })
                    @Html.ActionLink("Detalji", "Details", "Proizvods", new { id = item.idProizvod }, new { @class = "btn btn-secondary" })
                </div>
                <hr />
            }
        }
        else
        {
            var kategorija = (string)Request.QueryString["Naziv"].ToLower().Trim();
            var filteredItems = Model.Where(p => p.Naziv.ToLower().Contains(kategorija));
            if (filteredItems.Any())
            {
                foreach (var item in filteredItems)
                {
                    <div style="border:solid 1px gray; border-radius:10px; display:inline-flex; flex-direction:column; min-width:300px; max-width:800px; min-height:100px">
                        <ol>
                            <li><b>Naziv:</b>@Html.DisplayFor(modelItem => item.Naziv)</li>
                            <br />
                            <li><b>Proizvođač:</b>@Html.DisplayFor(modelItem => item.Proizvodac)</li>
                            <br />
                            <li><b>Cijena:</b>@Html.DisplayFor(modelItem => item.Cijena)</li>
                        </ol>
                        @Html.ActionLink("Dodaj u košaricu", "Details", "Proizvods", new { id = item.idProizvod }, new { @class = "btn btn-info" })
                        @Html.ActionLink("Detalji", "Details", "Proizvods", new { id = item.idProizvod }, new { @class = "btn btn-secondary" })
                    </div>
                    <hr />
                }
            }
            else
            {
                <h6>Nema rezultata za pretragu: @kategorija</h6>
            }

        }


    </div>

</main>